# SPDX-License-Identifier: GPL-2.0
# CFLAGS_teek.o := -DDEBUG

obj-$(CONFIG_TEE) += tee.o
tee-objs += tee_core.o
tee-objs += tee_shm.o
tee-objs += tee_shm_pool.o
tee-objs += teek.o
obj-$(CONFIG_OPTEE) += optee/
