#ifndef _LDR_DISPATCHER_H_
#define _LDR_DISPATCHER_H_

#define MAX_PARAM_BUF_SIZE	256

enum ipu_func {
	IPU_PROBE,
	IPU_INIT_CHANNEL,
	IPU_UNINIT_CHANNEL,
	IPU_INIT_CHANNEL_BUFFER,
	IPU_UPDATE_CHANNEL_BUFFER,
	IPU_SELECT_BUFFER,
	IPU_ENABLE_CHANNEL,
	IPU_DISABLE_CHANNEL,
	IPU_ENABLE_CSI,
	IPU_DISABLE_CSI,
	IPU_REQUEST_IRQ,
	IPU_FREE_IRQ,
};

#endif